version: '3'
services:
  consulserver:
    image: "consul"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
    ports:
      - "8301:8301"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    volumes:
      - /tmp/consul:/tmp/consul
    command: "agent -server -bootstrap -ui -data-dir=/tmp/consul -client=0.0.0.0 -bind='{{ GetInterfaceIP \"eth0\" }}'"
  configserver:
    image: ron/config-server:1.0-SNAPSHOT
    ports:
      - "8888:8888"
    environment:
      - GIT_URL=${GIT_URL}
      - GIT_CREDENTIALS_USERNAME=${GIT_CREDENTIALS_USERNAME}
      - GIT_CREDENTIALS_PASSWORD=${GIT_CREDENTIALS_PASSWORD}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUL_URL=${CONSUL_URL}
      - CONSUL_PORT=${CONSUL_PORT}
    links:
      - consulserver:consulserver
  userservice:
    image: ron/userservice:1.0-SNAPSHOT
    ports:
      - "8085:8085"
    environment:
      - PROFILE=dev
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUL_URL=${CONSUL_URL}
      - CONSUL_PORT=${CONSUL_PORT}
      - SERVER_PORT=8085
      - CONFIG_URL=${CONFIG_URL}
      - CONFIG_PORT=${CONFIG_PORT}
    links:
      - consulserver:consulserver
      - configserver:configserver
  inventoryservice:
    image: ron/inventoryservice:1.0-SNAPSHOT
    ports:
      - "8086:8086"
    environment:
      - PROFILE=dev
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUL_URL=${CONSUL_URL}
      - CONSUL_PORT=${CONSUL_PORT}
      - SERVER_PORT=8086
      - CONFIG_URL=${CONFIG_URL}
      - CONFIG_PORT=${CONFIG_PORT}
    links:
      - consulserver:consulserver
      - configserver:configserver