server:
  port: 8888
spring:
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}
        prefer-ip-address: true
      host: ${CONSUL_URL:localhost}
      port: ${CONSUL_PORT:8500}
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: ${GIT_URL}
          username: ${GIT_CREDENTIALS_USERNAME}
          password: ${GIT_CREDENTIALS_PASSWORD}
          searchPaths: "*"