version: '3'
services:
  consulserver:
    image: "consul"
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
    ports:
      - "8301:8301"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0 -bind='{{ GetInterfaceIP \"eth0\" }}'"
  database:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  configserver:
    image: ron/configserver:1.0-SNAPSHOT
    ports:
      - "8888"
    environment:
      - GIT_URL=${GIT_URL}
      - GIT_CREDENTIALS_USERNAME=${GIT_CREDENTIALS_USERNAME}
      - GIT_CREDENTIALS_PASSWORD=${GIT_CREDENTIALS_PASSWORD}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUL_URL=${CONSUL_URL}
      - CONSUL_PORT=${CONSUL_PORT}
  gatewayservice:
    image: ron/gatewayservice:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - PROFILE=default
      - SERVER_PORT=8080
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUL_URL=${CONSUL_URL}
      - CONSUL_PORT=${CONSUL_PORT}
  userservice:
    image: ron/userservice:1.0-SNAPSHOT
    ports:
      - "8085"
    environment:
      - PROFILE=default
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUL_URL=${CONSUL_URL}
      - CONSUL_PORT=${CONSUL_PORT}
      - SERVER_PORT=8085
      - CONFIG_URL=${CONFIG_URL}
      - CONFIG_PORT=${CONFIG_PORT}
      - DB_PORT=${DB_PORT}
  inventoryservice:
    image: ron/inventoryservice:1.0-SNAPSHOT
    ports:
      - "8086"
    environment:
      - PROFILE=default
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUL_URL=${CONSUL_URL}
      - CONSUL_PORT=${CONSUL_PORT}
      - SERVER_PORT=8086
      - CONFIG_URL=${CONFIG_URL}
      - CONFIG_PORT=${CONFIG_PORT}
      - DB_PORT=${DB_PORT}
  authservice:
    image: ron/authservice:1.0-SNAPSHOT
    ports:
      - "8901"
    environment:
      - PROFILE=default
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - CONSUL_URL=${CONSUL_URL}
      - CONSUL_PORT=${CONSUL_PORT}
      - SERVER_PORT=8901
      - CONFIG_URL=${CONFIG_URL}
      - CONFIG_PORT=${CONFIG_PORT}
      - DB_PORT=${DB_PORT}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}